version: '3.7'

services:

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      # Requires env variable: export APP_ENV=development OR export APP_ENV=production
      dockerfile: node.${APP_ENV}.dockerfile
      args:
        buildversion: 1
    ports:
      # Short Syntax 3 options:
      # - HOST:CONTAINER
      # - CONTAINER (an ephemeral host port is chosen for the host port)
      # - IPADDR:HOST:CONTAINER
      # When mapping ports in the HOST:CONTAINER format,
      # you may experience erroneous results when using a container port lower than 60,
      # because YAML parses numbers in the format xx:yy as a base-60 value.

      # - "3000:3000"

      # Long Syntax:
      # allows the configuration of additional fields that can’t be expressed in the short form
      - target: 3000
        published: 3000
        protocol: tcp # tcp or udp
        mode: host # host or ingress
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge